/**
 * @file ctxlayout.h
 * @author theflysong (song_of_the_fly@163.com)
 * @brief Hart 与 RISC-V 上下文布局常量
 * @version alpha-1.0.0
 * @date 2026-05-27
 *
 * @copyright Copyright (c) 2026
 *
 */

#pragma once

#define HART_CONTEXT_SIZE 512UL
#define MAX_HARTS 32UL

#define CTX_SLOT_SIZE 8UL
#define CTX_SLOT_SHIFT 3UL
#define CTX_SLOT_OFFSET(slot) ((slot) << CTX_SLOT_SHIFT)

#define CTX_X1_SLOT 0UL
#define CTX_X2_SLOT 1UL
#define CTX_X3_SLOT 2UL
#define CTX_X4_SLOT 3UL
#define CTX_X5_SLOT 4UL
#define CTX_X6_SLOT 5UL
#define CTX_X7_SLOT 6UL
#define CTX_X8_SLOT 7UL
#define CTX_X9_SLOT 8UL
#define CTX_X10_SLOT 9UL
#define CTX_X11_SLOT 10UL
#define CTX_X12_SLOT 11UL
#define CTX_X13_SLOT 12UL
#define CTX_X14_SLOT 13UL
#define CTX_X15_SLOT 14UL
#define CTX_X16_SLOT 15UL
#define CTX_X17_SLOT 16UL
#define CTX_X18_SLOT 17UL
#define CTX_X19_SLOT 18UL
#define CTX_X20_SLOT 19UL
#define CTX_X21_SLOT 20UL
#define CTX_X22_SLOT 21UL
#define CTX_X23_SLOT 22UL
#define CTX_X24_SLOT 23UL
#define CTX_X25_SLOT 24UL
#define CTX_X26_SLOT 25UL
#define CTX_X27_SLOT 26UL
#define CTX_X28_SLOT 27UL
#define CTX_X29_SLOT 28UL
#define CTX_X30_SLOT 29UL
#define CTX_X31_SLOT 30UL

#define CTX_SEPC_SLOT 31UL
#define CTX_SSTATUS_SLOT 32UL
#define CTX_KSTACK_SP_SLOT 33UL
#define CTX_SLOT_COUNT 34UL

#define CTX_RA_SLOT CTX_X1_SLOT
#define CTX_SP_SLOT CTX_X2_SLOT
#define CTX_GP_SLOT CTX_X3_SLOT
#define CTX_TP_SLOT CTX_X4_SLOT
#define CTX_T0_SLOT CTX_X5_SLOT
#define CTX_T1_SLOT CTX_X6_SLOT
#define CTX_T2_SLOT CTX_X7_SLOT
#define CTX_S0_SLOT CTX_X8_SLOT
#define CTX_S1_SLOT CTX_X9_SLOT
#define CTX_A0_SLOT CTX_X10_SLOT
#define CTX_A1_SLOT CTX_X11_SLOT
#define CTX_A2_SLOT CTX_X12_SLOT
#define CTX_A3_SLOT CTX_X13_SLOT
#define CTX_A4_SLOT CTX_X14_SLOT
#define CTX_A5_SLOT CTX_X15_SLOT
#define CTX_A6_SLOT CTX_X16_SLOT
#define CTX_A7_SLOT CTX_X17_SLOT
#define CTX_S2_SLOT CTX_X18_SLOT
#define CTX_S3_SLOT CTX_X19_SLOT
#define CTX_S4_SLOT CTX_X20_SLOT
#define CTX_S5_SLOT CTX_X21_SLOT
#define CTX_S6_SLOT CTX_X22_SLOT
#define CTX_S7_SLOT CTX_X23_SLOT
#define CTX_S8_SLOT CTX_X24_SLOT
#define CTX_S9_SLOT CTX_X25_SLOT
#define CTX_S10_SLOT CTX_X26_SLOT
#define CTX_S11_SLOT CTX_X27_SLOT
#define CTX_T3_SLOT CTX_X28_SLOT
#define CTX_T4_SLOT CTX_X29_SLOT
#define CTX_T5_SLOT CTX_X30_SLOT
#define CTX_T6_SLOT CTX_X31_SLOT

#define CTX_GPR_SLOT(xn) ((xn) - 1UL)
